### ISSUE TITLE
Je n'arrive pas a faire en sorte que la traduction fonctionne

### ISSUE THREAD

**Issue by sebalab** [pH7Software/pH7-Internationalization#1]
Bonjour

J'ai traduit tout le fichier po et remis tout dans le serveur comme indiqué, mais lorsque je passe en francais je n'est rien de vraiement traduit a part les gros titres sinon rien d'autres...

comment faire j'ai beau relire je ne vois pas ce que j'ai loupé comme etape.

D'avance merci.
cordialement

**Comment by pH-7** [comment]
Pouvez-vous créer un ticket dans votre espace http://clients.hizup.com/clientarea.php
Avec les détails FTP pour ainsi vérifier si il y a quelque chose d'incorrecte là
