### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by xavatar** [pH7Software/pH7-Internationalization#17]
Hello,
i installed ph7 today and i can not put the translation. I have the following error message:

ALTER TABLE ph7_meta_main MODIFY metaCopyright varchar(55)
MySQL a répondu: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '------
ALTER TABLE ph7_meta_main MODIFY metaCopyright varchar(55)' at line 1

I checked the db of ph7, and I do not see a ph7_meta_main table which explains the error, is this normal?

Thx for reply.

**Comment by pH-7** [comment]
Please don't run the comment
```
-----
-- Replace "ph7_" by your prefix set in "~/_protected/app/configs/config.ini" [database] prefix variable
-----
```

Just run the code after it.

That comment was causing SQL error, because of the extra `-` dashes :)


Thanks.
