### ISSUE TITLE
French Language Translate

### ISSUE THREAD

**Issue by MS-DOS2** [pH7Software/pH7-Internationalization#31]
Hello, I have translated the global.po file into French at around 98%. Can I share it on ph7-Internationalization?

**Comment by pH-7** [comment]
Absolutely @randomtech2! That's amazing!!! 🎉

**Comment by pH-7** [comment]
Just open a PR (pull request) and I will be glad to review it for you 🤗

**Comment by pH-7** [comment]
- https://openclassrooms.com/fr/courses/2342361-gerez-votre-code-avec-git-et-github/2433731-contribuez-a-des-projets-open-source
- https://openclassrooms.com/fr/courses/2342361-gerez-votre-code-avec-git-et-github/2433731-contribuez-a-des-projets-open-source
- And the official doc, in English though; https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by pH-7** [comment]
Otherwise, if that's too difficult, please just attach the zip of your translation, here of this issue (drag and drop it) and I will unzip the files and add it to the repo :)

**Comment by MS-DOS2** [comment]
I put the files in zip it's simpler
[global.zip](https://github.com/pH7Software/pH7-Internationalization/files/4443215/global.zip)

**Comment by pH-7** [comment]
Awesome :)

**Comment by pH-7** [comment]
I just updated it -> https://github.com/pH7Software/pH7-Internationalization/commit/a2481d63e1751f2c3d3e042bf10d9a57bc350ec1

Later on, feel free to open a new issue containing any new updates of the translation. I REALLY appreciate it! You rock! 

Take care :)

**Comment by MS-DOS2** [comment]
Thank you no problem I will update the translation if necessary

**Comment by randomtech2** [comment]
hello here is the translation update 
[global.zip](https://github.com/pH7Software/pH7-Internationalization/files/4567422/global.zip)

**Comment by Salva99999** [comment]
Hello, I need someone to help me. I'm not getting anywhere with my project. I love this template, but I can't translate it. I'm testing with WAMP and even though I'm following the whole procedure, my site is still in US. Is it possible to modify the geographical dafault?
