### ISSUE TITLE
Translation of home page text

### ISSUE THREAD

**Issue by jeffricofc** [pH7Software/pH7-Internationalization#8]
How can I translate the text on home page (Meet & date amazing people near "Minneapolis"!)?
 I meant in which file it is.
![screenshot_1](https://user-images.githubusercontent.com/37934272/39964184-f72d55e6-5654-11e8-93cf-f7c2ef8c7dbc.png)

**Comment by pH-7** [comment]
Hi @developer1sirimarketing 
Like I just told you by email, for this string, you will have to add it manually into the PO Portuguese file.

Add the following into it
```
#: _protected/data/cache/pH7tpl_compile/user_92496e072f4a216a2e22292546425ec0/base/main/user_promo_block.inc.cpl.php:19
msgid "Meet &amp; date amazing people near %0%!"
msgstr "" # Your Portuguese Translation these
```

Hopefully, that helps ;)
