### ISSUE TITLE
Translation lines

### ISSUE THREAD

**Issue by jeffricofc** [pH7Software/pH7-Internationalization#9]
How can I translate the text on home page (Meet & date amazing people near "Minneapolis"!)?
I meant in which file it is.

I added the lines below on my portuguese PO file as you have said before and it did not work.

#: _protected/data/cache/pH7tpl_compile/user_92496e072f4a216a2e22292546425ec0/base/main/user_promo_block.inc.cpl.php:19
msgid "Meet &amp; date amazing people near %0%!"
msgstr "" # Your Portuguese Translation these

Any ideia about it?

**Comment by jeffricofc** [comment]
Sorry mate. It has been sorted.

**Comment by jeffricofc** [comment]
You can close it.

**Comment by pH-7** [comment]
Happy to hear that! 😃👍
